# put hostname (i.e., Node) names in here, not manager (i.e., ILOM or DRAC) names
#
#Rack 0
0:
  0: compute-0-0
  1: compute-0-1
  2: compute-0-2
  3: compute-0-3
  4: compute-0-4
  5: compute-0-5
  6: compute-0-6
  7: compute-0-7
  8: compute-0-8
  9: compute-0-9
  10: compute-0-10
  11: compute-0-11
  12: compute-0-12
  13: hnode
  14: grid2
# Rack 1
1:
  0: compute-1-0
  1: compute-1-1
  2: compute-1-2
  3: compute-1-3
  4: compute-1-4
  5: compute-1-5
  6: compute-1-6
  7: compute-1-7
  8: compute-1-8
  9: compute-1-9
  10: compute-1-10
  11: compute-1-11
  12: compute-1-12
  13: compute-1-13
  14: compute-1-14
  15: compute-1-15
  16: compute-1-16
  17: compute-1-17
  18: compute-1-18
  19: compute-1-19
  20: compute-1-20
  21: compute-1-21
  22: compute-1-22
  23: compute-1-23
  24: compute-1-24
  25: compute-1-25
  26: compute-1-26
  27: compute-1-27
  28: compute-1-28
  29: compute-1-29
  30: compute-1-30
  31: compute-1-31
  32: compute-1-32
  33: compute-1-33
  34: compute-1-34
  35: compute-1-35
  36: compute-1-36
# Rack 2
2:
  0: compute-2-0
  1: compute-2-1
  2: compute-2-2
  3: compute-2-3
  4: compute-2-4
  5: compute-2-5
  6: compute-2-6
  7: compute-2-7
  8: compute-2-8
  9: compute-2-9
  10: compute-2-10
  11: compute-2-11
  12: compute-2-12
  13: compute-2-13
  14: compute-2-14
  15: compute-2-15
  16: compute-2-16
  17: compute-2-17
  18: compute-2-18
  19: compute-2-19
  20: compute-2-20
  21: compute-2-21
  22: compute-2-22
  23: compute-2-23
# Rack3
3:
  0: compute-3-0
  1: compute-3-1
  2: compute-3-2
  3: compute-3-3
  4: compute-3-4
  5: compute-3-5
  6: compute-3-6
  7: compute-3-7
  8: compute-3-8
  9: compute-3-9
  10: compute-3-10
  11: compute-3-11
  12: compute-3-12
  13: compute-3-13
  14: compute-3-14
  15: compute-3-15
  16: compute-3-16
  17: compute-3-17
  18: compute-3-18
  19: compute-3-19
  20: compute-3-20
  21: compute-3-21
  22: compute-3-22
  23: compute-3-23
  24: compute-3-24
  25: compute-3-25
  26: compute-3-26
  27: compute-3-27
  28: compute-3-28
  29: compute-3-29
  30: compute-3-30
# Rack 4
4: 
  0: cortex2
  1: compute-4-0
  2: compute-4-1
  3: compute-4-2 
